name: Build Hugo Site

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.142.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Cache Hugo binary
        id: cache-hugo
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/hugo
          key: hugo-${{ env.HUGO_VERSION }}

      - name: Install Hugo CLI
        if: steps.cache-hugo.outputs.cache-hit != 'true'
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Cache Hugo build cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/hugo_cache
          key: hugo-cache-${{ hashFiles('homepage/content/**', 'homepage/layouts/**', 'homepage/static/**') }}
          restore-keys: |
            hugo-cache-

      - name: Build site
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          cd homepage
          hugo --minify

      - name: Upload artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./homepage/public

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
